package com.capysoft.tuevento.modules.language.domain.model;

import com.capysoft.tuevento.shared.domain.valueobject.TranslationSource;
import com.capysoft.tuevento.shared.domain.valueobject.TranslationStatus;

import java.util.Objects;

public class ActionTranslation {
    private Long translationId;
    private String action;
    private Long languageId;
    private String translatedDescription;
    private TranslationSource source;
    private TranslationStatus status;

    public ActionTranslation() {}

    public ActionTranslation(String action, Long languageId, String translatedDescription, 
                           TranslationSource source, TranslationStatus status) {
        this.action = action;
        this.languageId = languageId;
        this.translatedDescription = translatedDescription;
        this.source = source;
        this.status = status;
    }

    // Business validations
    public void validateTranslatedContent() {
        if (action == null || action.trim().isEmpty()) {
            throw new IllegalArgumentException("Action name cannot be null or empty");
        }
        if (translatedDescription == null || translatedDescription.trim().isEmpty()) {
            throw new IllegalArgumentException("Translated description cannot be null or empty");
        }
    }

    public void normalizeContent() {
        if (action != null) {
            this.action = action.trim();
        }
        if (translatedDescription != null) {
            this.translatedDescription = translatedDescription.trim();
        }
    }

    public void markAsPublished() {
        if (status != TranslationStatus.DRAFT && status != TranslationStatus.PENDING_REVIEW) {
            throw new IllegalStateException("Only DRAFT or PENDING_REVIEW translations can be published");
        }
        this.status = TranslationStatus.PUBLISHED;
    }

    public void markAsPendingReview() {
        if (status != TranslationStatus.DRAFT) {
            throw new IllegalStateException("Only DRAFT translations can be marked as pending review");
        }
        this.status = TranslationStatus.PENDING_REVIEW;
    }

    public boolean isAutoGenerated() {
        return TranslationSource.MACHINE.equals(this.source);
    }

    public boolean isManuallyCreated() {
        return TranslationSource.MANUAL.equals(this.source);
    }

    // Getters and Setters
    public Long getTranslationId() {
        return translationId;
    }

    public void setTranslationId(Long translationId) {
        this.translationId = translationId;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public Long getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    public String getTranslatedDescription() {
        return translatedDescription;
    }

    public void setTranslatedDescription(String translatedDescription) {
        this.translatedDescription = translatedDescription;
    }

    public TranslationSource getSource() {
        return source;
    }

    public void setSource(TranslationSource source) {
        this.source = source;
    }

    public TranslationStatus getStatus() {
        return status;
    }

    public void setStatus(TranslationStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ActionTranslation that = (ActionTranslation) o;
        return Objects.equals(action, that.action) &&
               Objects.equals(languageId, that.languageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action, languageId);
    }
}