package com.capysoft.tuevento.modules.language.domain.model;

import com.capysoft.tuevento.modules.language.domain.enums.TranslationSource;
import com.capysoft.tuevento.modules.language.domain.enums.TranslationStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ModuleTranslation {

    private Integer translationId;
    private String module;
    private Integer languageId;
    private String translatedName;
    private TranslationSource source;
    private TranslationStatus status;

    public static ModuleTranslation create(
            String module,
            Integer languageId,
            String translatedName,
            TranslationSource source) {
        return ModuleTranslation.builder()
                .module(module)
                .languageId(languageId)
                .translatedName(translatedName)
                .source(source)
                .status(TranslationStatus.DRAFT)
                .build();
    }

    public void updateTranslation(String translatedName) {
        this.translatedName = translatedName;
        this.status = TranslationStatus.DRAFT;
    }

    public void publish() {
        this.status = TranslationStatus.PUBLISHED;
    }

    public void markForReview() {
        this.status = TranslationStatus.PENDING_REVIEW;
    }

    public boolean isPublished() {
        return TranslationStatus.PUBLISHED.equals(this.status);
    }

    public boolean isPendingReview() {
        return TranslationStatus.PENDING_REVIEW.equals(this.status);
    }

    public boolean isDraft() {
        return TranslationStatus.DRAFT.equals(this.status);
    }

    public boolean isAutoGenerated() {
        return TranslationSource.AUTO.equals(this.source);
    }

    public boolean isManuallyCreated() {
        return TranslationSource.MANUAL.equals(this.source);
    }
}