package com.capysoft.tuevento.modules.language.domain.model;

import com.capysoft.tuevento.shared.domain.valueobject.TranslationSource;
import com.capysoft.tuevento.shared.domain.valueobject.TranslationStatus;

import java.util.Objects;

public class ModuleTranslation {
    private Integer translationId;
    private String module;
    private Integer languageId;
    private String translatedName;
    private TranslationSource source;
    private TranslationStatus status;

    public ModuleTranslation() {}

    public ModuleTranslation(String module, Integer languageId, String translatedName, 
                           TranslationSource source, TranslationStatus status) {
        this.module = module;
        this.languageId = languageId;
        this.translatedName = translatedName;
        this.source = source;
        this.status = status;
    }

    // Business validations
    public void validateTranslatedContent() {
        if (module == null || module.trim().isEmpty()) {
            throw new IllegalArgumentException("Module name cannot be null or empty");
        }
        if (translatedName == null || translatedName.trim().isEmpty()) {
            throw new IllegalArgumentException("Translated name cannot be null or empty");
        }
    }

    public void normalizeContent() {
        if (module != null) {
            this.module = module.trim();
        }
        if (translatedName != null) {
            this.translatedName = translatedName.trim();
        }
    }

    public void markAsPublished() {
        if (status != TranslationStatus.DRAFT && status != TranslationStatus.PENDING_REVIEW) {
            throw new IllegalStateException("Only DRAFT or PENDING_REVIEW translations can be published");
        }
        this.status = TranslationStatus.PUBLISHED;
    }

    public void markAsPendingReview() {
        if (status != TranslationStatus.DRAFT) {
            throw new IllegalStateException("Only DRAFT translations can be marked as pending review");
        }
        this.status = TranslationStatus.PENDING_REVIEW;
    }

    public boolean isAutoGenerated() {
        return TranslationSource.MACHINE.equals(this.source);
    }

    public boolean isManuallyCreated() {
        return TranslationSource.MANUAL.equals(this.source);
    }

    // Getters and Setters
    public Integer getTranslationId() {
        return translationId;
    }

    public void setTranslationId(Integer translationId) {
        this.translationId = translationId;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public Integer getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    public String getTranslatedName() {
        return translatedName;
    }

    public void setTranslatedName(String translatedName) {
        this.translatedName = translatedName;
    }

    public TranslationSource getSource() {
        return source;
    }

    public void setSource(TranslationSource source) {
        this.source = source;
    }

    public TranslationStatus getStatus() {
        return status;
    }

    public void setStatus(TranslationStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ModuleTranslation that = (ModuleTranslation) o;
        return Objects.equals(module, that.module) &&
               Objects.equals(languageId, that.languageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(module, languageId);
    }
}