package com.capysoft.tuevento.modules.language.domain.model;

import com.capysoft.tuevento.shared.domain.valueobject.TranslationSource;
import com.capysoft.tuevento.shared.domain.valueobject.TranslationStatus;

import java.util.Objects;

public class NotificationTypeTranslation {
    private Integer translationId;
    private Integer notificationTypeId;
    private Integer languageId;
    private String translatedName;
    private String translatedDescription;
    private TranslationSource source;
    private TranslationStatus status;

    public NotificationTypeTranslation() {}

    public NotificationTypeTranslation(Integer notificationTypeId, Integer languageId, String translatedName, 
                                     String translatedDescription, TranslationSource source, 
                                     TranslationStatus status) {
        this.notificationTypeId = notificationTypeId;
        this.languageId = languageId;
        this.translatedName = translatedName;
        this.translatedDescription = translatedDescription;
        this.source = source;
        this.status = status;
    }

    // Business validations
    public void validateTranslatedContent() {
        if (translatedName == null || translatedName.trim().isEmpty()) {
            throw new IllegalArgumentException("Translated name cannot be null or empty");
        }
        if (translatedDescription == null || translatedDescription.trim().isEmpty()) {
            throw new IllegalArgumentException("Translated description cannot be null or empty");
        }
    }

    public void normalizeContent() {
        if (translatedName != null) {
            this.translatedName = translatedName.trim();
        }
        if (translatedDescription != null) {
            this.translatedDescription = translatedDescription.trim();
        }
    }

    public void markAsPublished() {
        if (status != TranslationStatus.DRAFT && status != TranslationStatus.PENDING_REVIEW) {
            throw new IllegalStateException("Only DRAFT or PENDING_REVIEW translations can be published");
        }
        this.status = TranslationStatus.PUBLISHED;
    }

    public void markAsPendingReview() {
        if (status != TranslationStatus.DRAFT) {
            throw new IllegalStateException("Only DRAFT translations can be marked as pending review");
        }
        this.status = TranslationStatus.PENDING_REVIEW;
    }

    public boolean isAutoGenerated() {
        return TranslationSource.MACHINE.equals(this.source);
    }

    public boolean isManuallyCreated() {
        return TranslationSource.MANUAL.equals(this.source);
    }

    // Getters and Setters
    public Integer getTranslationId() {
        return translationId;
    }

    public void setTranslationId(Integer translationId) {
        this.translationId = translationId;
    }

    public Integer getNotificationTypeId() {
        return notificationTypeId;
    }

    public void setNotificationTypeId(Integer notificationTypeId) {
        this.notificationTypeId = notificationTypeId;
    }

    public Integer getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    public String getTranslatedName() {
        return translatedName;
    }

    public void setTranslatedName(String translatedName) {
        this.translatedName = translatedName;
    }

    public String getTranslatedDescription() {
        return translatedDescription;
    }

    public void setTranslatedDescription(String translatedDescription) {
        this.translatedDescription = translatedDescription;
    }

    public TranslationSource getSource() {
        return source;
    }

    public void setSource(TranslationSource source) {
        this.source = source;
    }

    public TranslationStatus getStatus() {
        return status;
    }

    public void setStatus(TranslationStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NotificationTypeTranslation that = (NotificationTypeTranslation) o;
        return Objects.equals(notificationTypeId, that.notificationTypeId) &&
               Objects.equals(languageId, that.languageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(notificationTypeId, languageId);
    }
}