apiVersion: v1
kind: Secret
metadata:
  name: tu-evento-secrets
type: Opaque
data:
  db-username: cG9zdGdyZXM=
  db-password: c2VjcmV0
  minio-access-key: bWluaW9hZG1pbg==
  minio-secret-key: bWluaW9wYXNzd29yZA==
  jwt-secret: bWlDbGF2ZVNlY3JldGFTdXBlckxhcmdhUGFyYUpXVFR1RXZlbnRvMjAyNiEh
  google-client-id: dGVzdC1nb29nbGUtY2xpZW50LWlk
  google-client-secret: dGVzdC1nb29nbGUtc2VjcmV0
  facebook-client-id: dGVzdC1mYWNlYm9vay1jbGllbnQtaWQ=
  facebook-client-secret: dGVzdC1mYWNlYm9vay1zZWNyZXQ=
  admin-email: dGVzdEBnbWFpbC5jb20=
  admin-password: dGVzdHBhc3N3b3Jk
  admin-alias: VGVzdEFkbWlu
  mail-username: dGVzdEBnbWFpbC5jb20=
  mail-password: dGVzdHBhc3N3b3Jk