/**
 * Paletas de tema predefinidas para la app.
 * Cada paleta sobreescribe los tokens de colors.js.
 * Los valores que no se especifican heredan del tema base (DARK).
 */

export const THEMES = [
  {
    id: "DARK",
    name: "Oscuro",
    description: "Tema por defecto — morado profundo",
    emoji: "🌙",
    preview: {
      background: "#1E0A3C",
      primary:    "#7C3AED",
      accent:     "#A78BFA",
    },
    palette: {
      background:   "#1E0A3C",
      surface:      "#2D1B4E",
      surfaceAlt:   "#3D2B5E",
      primary:      "#7C3AED",
      primaryDark:  "#6D28D9",
      accent:       "#A78BFA",
      textPrimary:  "#FFFFFF",
      textSecondary:"#9CA3AF",
      textMuted:    "#6B7280",
      error:        "#EF4444",
      errorBg:      "#EF444422",
      success:      "#059669",
      successBg:    "#05966922",
      gradientBg:      ["#1E0A3C", "#2D1B4E", "#1E0A3C"],
      gradientPrimary: ["#7C3AED", "#6D28D9"],
    },
  },
  {
    id: "LIGHT",
    name: "Claro",
    description: "Fondo blanco con acento violeta",
    emoji: "☀️",
    preview: {
      background: "#F8F7FF",
      primary:    "#7C3AED",
      accent:     "#8B5CF6",
    },
    palette: {
      background:   "#F8F7FF",
      surface:      "#EDEDFF",
      surfaceAlt:   "#DDD9FF",
      primary:      "#7C3AED",
      primaryDark:  "#6D28D9",
      accent:       "#8B5CF6",
      textPrimary:  "#1A0A2E",
      textSecondary:"#4B5563",
      textMuted:    "#9CA3AF",
      error:        "#EF4444",
      errorBg:      "#EF444422",
      success:      "#059669",
      successBg:    "#05966922",
      gradientBg:      ["#F8F7FF", "#EDEDFF", "#F8F7FF"],
      gradientPrimary: ["#7C3AED", "#6D28D9"],
    },
  },
  {
    id: "VIBRANT",
    name: "Vibrante",
    description: "Negro intenso con acento neón",
    emoji: "⚡",
    preview: {
      background: "#0D0D0D",
      primary:    "#FF4081",
      accent:     "#FFEB3B",
    },
    palette: {
      background:   "#0D0D0D",
      surface:      "#1A1A1A",
      surfaceAlt:   "#2A2A2A",
      primary:      "#FF4081",
      primaryDark:  "#E91E63",
      accent:       "#FFEB3B",
      textPrimary:  "#FFFFFF",
      textSecondary:"#BDBDBD",
      textMuted:    "#757575",
      error:        "#FF5252",
      errorBg:      "#FF525222",
      success:      "#69F0AE",
      successBg:    "#69F0AE22",
      gradientBg:      ["#0D0D0D", "#1A1A1A", "#0D0D0D"],
      gradientPrimary: ["#FF4081", "#E91E63"],
    },
  },
  {
    id: "ACCESSIBLE",
    name: "Accesible",
    description: "Alto contraste para mejor legibilidad",
    emoji: "♿",
    preview: {
      background: "#FFFFFF",
      primary:    "#005FCC",
      accent:     "#E65100",
    },
    palette: {
      background:   "#FFFFFF",
      surface:      "#F0F4FF",
      surfaceAlt:   "#D6E4FF",
      primary:      "#005FCC",
      primaryDark:  "#004499",
      accent:       "#E65100",
      textPrimary:  "#000000",
      textSecondary:"#333333",
      textMuted:    "#666666",
      error:        "#CC0000",
      errorBg:      "#CC000022",
      success:      "#006600",
      successBg:    "#00660022",
      gradientBg:      ["#FFFFFF", "#F0F4FF", "#FFFFFF"],
      gradientPrimary: ["#005FCC", "#004499"],
    },
  },
];

export const DEFAULT_THEME_ID = "DARK";
