spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tuevento_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.capysoft: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
  mail:
    from: ${MAIL_USERNAME}
