spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tuevento_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.capysoft: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
